doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        driver: "pdo_mysql"
        options:
            # Keep existing SSL options
            !php/const PDO::MYSQL_ATTR_SSL_KEY: "%env(MYSQL_SSL_KEY)%"
            !php/const PDO::MYSQL_ATTR_SSL_CERT: "%env(MYSQL_SSL_CERT)%"
            !php/const PDO::MYSQL_ATTR_SSL_CA: "%env(MYSQL_SSL_CA)%"
            !php/const PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT: false
            # Add init commands as numeric keys
            1001: "SET NAMES latin1 COLLATE latin1_general_ci"
            1002: "SET SESSION net_read_timeout=3600"
            1003: "SET SESSION net_write_timeout=3600"
            1004: "SET SESSION wait_timeout=28800"
            1005: "SET SESSION interactive_timeout=28800"
            # Add connection timeout setting
            !php/const PDO::ATTR_TIMEOUT: 60

        profiling_collect_backtrace: "%kernel.debug%"
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Entity"
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: "%kernel.build_dir%/doctrine/orm/Proxies"
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
