version: '3.8'
services:
  database:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database_data:/var/lib/mysql
      - ./create-power-bi-ronlyuser.sql:/docker-entrypoint-initdb.d/create-power-bi-ronlyuser.sql
    ports:
      - "3307:3306"
    networks:
      vpcbr:
        ipv4_address: 172.22.0.2
    labels:
      - "traefik.enable=false"
      # - "traefik.http.routers.database-efnc.rule=PathPrefix(`/database-efnc`)"
      # - "traefik.http.routers.database-efnc.entrypoints=mariadb"
      # - "traefik.tcp.routers.tcp-database-efnc.entrypoints=mariadb"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_ABSOLUTE_URI: http://${HOSTNAME}/efncpma/
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadminefnc.rule=PathPrefix(`/efncpma`)"
      - "traefik.http.routers.phpmyadminefnc.middlewares=strip-phpmyadminefnc-prefix"
      - "traefik.http.middlewares.strip-phpmyadminefnc-prefix.stripPrefix.prefixes=/efncpma"
      - "traefik.http.routers.phpmyadminefnc.entrypoints=web"
    networks:
      vpcbr:
        ipv4_address: 172.22.0.3
    depends_on:
      - database


networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
