apiVersion: v1
kind: Service
metadata:
  name: efnc-database-service
spec:
  selector:
    app: efnc-database
  ports:
    - port: 3307
---
apiVersion: v1
kind: Pod
metadata:
  name: efnc-database-pod
  labels:
    app: efnc-database
spec:
  restartPolicy: Always
  containers:
    - name: database
      image: docker.io/library/mariadb:latest
      env:
        - name: MARIADB_ROOT_PASSWORD_FILE
          value: run/secrets/root_password
        - name: MARIADB_DATABASE_FILE
          value: run/secrets/database_name
        - name: MARIADB_USER_FILE
          value: run/secrets/database_user
        - name: MARIADB_PASSWORD_FILE
          value: run/secrets/database_password
      ports:
        - containerPort: 3307
      volumeMounts :
        - name: secrets
          mountPath: /run/secrets
          readOnly: true
        - mountPath: /var/lib/mysql
          name: database-data
  dnsPolicy: Default
  volumes:
    - name: secrets
      hostPath:
        path: ./secrets
        type: Directory
    - hostPath:
        path: ./database_data
        type: DirectoryOrCreate
      name: database-data
---
apiVersion: v1
kind: Pod
metadata:
  name: efnc-phpmyadmin-pod
  labels:
    app: efnc-phpmyadmin
    traefik.enable: true
    traefik.http.routers.efnc-phpmyadmin.rule: PathPrefix(`/efncpma`)
    traefik.http.routers.efnc-phpmyadmin.entrypoints: web
    traefik.http.routers.efnc-phpmyadmin.middlewares: strip-efnc-phpmyadmin-prefix
    traefik.http.services.efnc-phpmyadmin.loadbalancer.server.port: 80
    traefik.http.middlewares.strip-efnc-phpmyadmin-prefix.stripPrefix.prefixes: /efncpma
spec:
  restartPolicy: Always
  containers:
    - name: phpmyadmin
      image: docker.io/phpmyadmin/phpmyadmin
      env:
        - name: PMA_HOST
          value: efnc-database-pod
        - name: PMA_ABSOLUTE_URI
          value: http://sanclp0031/efncpma/
      volumeMounts:
        - mountPath: /etc/phpmyadmin/config.user.inc.php
          name: phpmyadmin-config
  dnsPolicy: Default
  volumes:
    - hostPath:
        path: ./config.user.inc.php
        type: File
      name: phpmyadmin-config
---
apiVersion: v1
kind: Pod
metadata:
  name: efnc-web-pod
  labels:
    app: efnc-web
    traefik.enable: true
    traefik.http.routers.efnc-web.rule: PathPrefix(`/efnc`)
    traefik.http.routers.efnc-web.entrypoints: web
    traefik.http.routers.efnc-web.middlewares: strip-efnc-web-prefix
    traefik.http.services.efnc-web.loadbalancer.server.port: 80
    traefik.http.middlewares.strip-efnc-web-prefix.stripPrefix.prefixes: /efnc
spec:
  restartPolicy: Always
  containers:
    - name: web
      image: ghcr.io/kiloutyg/efnc:main
      command: ["./dev-entrypoint.sh"]
      env:
        - name: no_proxy
          value: .ponet
        - name: http_proxy
          value: http://10.0.0.1:80
        - name: APP_TIMEZONE
          value: Europe/Paris
        - name: https_proxy
          value: http://10.0.0.1:80
      volumeMounts:
        - mountPath: /var/www
          name: web-data
  dnsPolicy: Default
  volumes:
    - hostPath:
        path: ./
        type: Directory
      name: web-data
