apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - port: 3306
---
apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: database
spec:
  restartPolicy: Always
  containers:
    - name: efnc
      image: docker.io/library/mariadb:latest
      env:
        - name: MARIADB_ROOT_PASSWORD_FILE
          value: run/secrets/root_password
        - name: MARIADB_DATABASE_FILE
          value: run/secrets/database_name
        - name: MARIADB_USER_FILE
          value: run/secrets/database_user
        - name: MARIADB_PASSWORD_FILE
          value: run/secrets/database_password
      ports:
        - containerPort: 3306
      volumeMounts :
        - name: secrets
          mountPath: /run/secrets
          readOnly: true
        - mountPath: /var/lib/mysql
          name: database-data
  dnsPolicy: Default
  volumes:
    - name: secrets
      hostPath:
        path: ./secrets
        type: Directory
    - hostPath:
        path: ./database_data
        type: DirectoryOrCreate
      name: database-data
---
apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin
  labels:
    app: efnc
    traefik.enable: true
    traefik.http.routers.phpmyadmin.rule: PathPrefix(`/efncpma`)
    traefik.http.routers.phpmyadmin.entrypoints: web
    traefik.http.routers.phpmyadmin.middlewares: strip-phpmyadmin-prefix
    traefik.http.services.phpmyadmin.loadbalancer.server.port: 80
    traefik.http.middlewares.strip-phpmyadmin-prefix.stripPrefix.prefixes: /efncpma
spec:
  restartPolicy: Always
  containers:
    - name: efnc
      image: docker.io/phpmyadmin/phpmyadmin
      env:
        - name: PMA_HOST
          value: database
        - name: PMA_ABSOLUTE_URI
          value: http://${HOSTNAME}/dappma/
      volumeMounts:
        - mountPath: /etc/phpmyadmin/config.user.inc.php
          name: phpmyadmin-config
  dnsPolicy: Default
  volumes:
    - hostPath:
        path: ./config.user.inc.php
        type: File
      name: phpmyadmin-config
---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: efnc
    traefik.enable: true
    traefik.http.routers.webdap.rule: PathPrefix(`/efnc`)
    traefik.http.routers.webdap.entrypoints: web
    traefik.http.routers.webdap.middlewares: strip-webdap-prefix
    traefik.http.services.webdap.loadbalancer.server.port: 80
    traefik.http.middlewares.strip-webdap-prefix.stripPrefix.prefixes: /efnc
spec:
  restartPolicy: Always
  containers:
    - name: efnc
      image: ghcr.io/${GITHUB_USER}/efnc:main
      command: ["./${APP_CONTEXT}-entrypoint.sh"]
      env:
        - name: no_proxy
          value: .ponet
        - name: http_proxy
          value: ${PROXY_ENV}
        - name: APP_TIMEZONE
          value: ${APP_TIMEZONE}
        - name: https_proxy
          value: ${PROXY_ENV}
      volumeMounts:
        - mountPath: /var/www
          name: web-data
  dnsPolicy: Default
  volumes:
    - hostPath:
        path: ./
        type: Directory
      name: web-data