when@dev:
    web_profiler_wdt:
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
        # prefix: /efnc/_wdt
        prefix: /_wdt


    web_profiler_profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
        # prefix: /efnc/_profiler
        prefix: /_profiler
